# Generated by Django 5.2.7 on 2025-10-24 16:23

import apps.forms.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('question', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('show_position', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FormCheckBoxField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.field')),
                ('check_box_names', models.JSONField(default=list, validators=[apps.forms.models.validate_string_list])),
                ('minimum', models.PositiveSmallIntegerField(default=0)),
                ('maximum', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            bases=('forms.field',),
        ),
        migrations.CreateModel(
            name='FormDateField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.field')),
                ('min_date', models.DateTimeField(blank=True, null=True)),
                ('max_date', models.DateTimeField(blank=True, null=True)),
                ('include_time', models.BooleanField(default=False)),
            ],
            bases=('forms.field',),
        ),
        migrations.CreateModel(
            name='FormNumberField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.field')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('decimal_allowed', models.BooleanField(default=False)),
            ],
            bases=('forms.field',),
        ),
        migrations.CreateModel(
            name='FormSelectField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.field')),
                ('options', models.JSONField(default=list, validators=[apps.forms.models.validate_string_list])),
            ],
            bases=('forms.field',),
        ),
        migrations.CreateModel(
            name='FormTextField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.field')),
                ('max_length', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            bases=('forms.field',),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=8, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form'),
        ),
        migrations.CreateModel(
            name='WelcomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('entrance_button_text', models.CharField(blank=True, max_length=50)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('form', 'position')},
        ),
    ]
