# Generated by Django 5.2.7 on 2025-10-25 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='form',
            name='is_public',
        ),
        migrations.AddField(
            model_name='form',
            name='access',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private (password)')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='form',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('form', 'position')},
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['access'], name='forms_form_access_f40357_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['slug'], name='forms_form_slug_64e4aa_idx'),
        ),
    ]
