# Generated by Django 5.2.7 on 2025-10-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_field_options_alter_form_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
