# Generated by Django 5.2.7 on 2025-10-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_deleted_at_form_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]