# Generated by Django 5.2.7 on 2025-10-24 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('type', models.CharField(choices=[('sequential', 'Sequential'), ('free_flow', 'Free flow')], default='sequential', max_length=20)),
                ('access', models.CharField(choices=[('public', 'Public'), ('private', 'Private (password)')], default='public', max_length=10)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_steps', to='forms.form')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.process')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.CheckConstraint(condition=models.Q(('access', 'public'), models.Q(('password', ''), _negated=True), _connector='OR'), name='password_required_when_private'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['process', 'order'], name='idx_process_order'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(fields=('process', 'order'), name='uniq_step_order_per_process'),
        ),
    ]
