# Generated by Django 5.2.7 on 2025-10-25 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0002_alter_field_options_alter_form_options_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('type', models.CharField(choices=[('sequential', 'Sequential'), ('free_flow', 'Free flow')], default='sequential', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_steps', to='forms.form')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.process')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='processes.process')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_processes', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='processes.processstep')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StepSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_submissions', to='forms.response')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='processes.processinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='processes.processstep')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['process', 'order'], name='idx_process_order'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(fields=('process', 'order'), name='uniq_step_order_per_process'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['process', 'status'], name='idx_procinst_proc_status'),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['access_token'], name='idx_procinst_token'),
        ),
        migrations.AddConstraint(
            model_name='processinstance',
            constraint=models.CheckConstraint(condition=models.Q(('started_by__isnull', True), ('access_token__isnull', False), _connector='OR'), name='guest_token_only_for_guest'),
        ),
        migrations.AddConstraint(
            model_name='stepsubmission',
            constraint=models.UniqueConstraint(fields=('instance', 'step'), name='uniq_instance_step'),
        ),
    ]
