# Generated by Django 5.2.7 on 2025-10-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinstance',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
