# Generated by Django 5.2.7 on 2025-10-24 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='processes.processstep')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='processes.process')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StepSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_submissions', to='forms.response')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='processes.processinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='processes.processstep')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['process', 'status'], name='idx_procinst_proc_status'),
        ),
        migrations.AlterUniqueTogether(
            name='stepsubmission',
            unique_together={('instance', 'step')},
        ),
    ]
