# Generated by Django 5.2.7 on 2025-10-28 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_field_options_alter_form_options_and_more'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='allow_skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stepsubmission',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processinstance',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stepsubmission',
            name='form_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_submissions', to='forms.response'),
        ),
    ]
