# Generated by Django 5.2.7 on 2025-10-24 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_processinstance_stepsubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='access',
        ),
        migrations.RemoveField(
            model_name='process',
            name='password',
        ),
        migrations.AddField(
            model_name='processinstance',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['access_token'], name='idx_procinst_token'),
        ),
        migrations.AddConstraint(
            model_name='processinstance',
            constraint=models.CheckConstraint(condition=models.Q(('started_by__isnull', True), ('access_token__isnull', True), _connector='OR'), name='guest_token_only_for_guest'),
        ),
    ]
